name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: martins-vds-org/reusable-workflows/.github/workflows/called-workflow.yml@main
    with:
      username: 'Vinny'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
